#!/usr/bin/env bash
# Idempotent RDS bootstrap for qwen-memory-mcp on Alibaba Cloud.
# Creates privileged + app accounts, database, public endpoint, IP whitelist.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REGION="${ALIBABA_REGION:-ap-southeast-1}"
DB_INSTANCE_ID="${RDS_INSTANCE_ID:-rm-gs56bv9zf5g03q9td}"
VSWITCH_CIDR="${RDS_VSWITCH_CIDR:-172.31.48.0/20}"
DB_NAME="qwen_memory"
APP_USER="qwen_memory"
SUPER_USER="qwen_admin"
PUBLIC_PREFIX="${RDS_PUBLIC_PREFIX:-qwenmemory}"
SECRETS_FILE="${RDS_SECRETS_FILE:-$ROOT/.env.rds.generated}"

if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
fi

if [[ -z "${ALIBABA_CLOUD_ACCESS_KEY_ID:-}" || -z "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:-}" ]]; then
  echo "bootstrap-rds: set ALIBABA_CLOUD_ACCESS_KEY_ID and ALIBABA_CLOUD_ACCESS_KEY_SECRET in .env" >&2
  exit 1
fi

gen_pass() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

if [[ ! -f "$SECRETS_FILE" ]]; then
  SUPER_PASS="$(gen_pass)"
  APP_PASS="$(gen_pass)"
  RDS_SUPER_PASSWORD="$SUPER_PASS"
  MYSQL_PASSWORD="$APP_PASS"
  cat > "$SECRETS_FILE" <<EOF
# Generated by deploy/bootstrap-rds.sh - gitignored, do not commit
RDS_SUPER_USER=$SUPER_USER
RDS_SUPER_PASSWORD=$SUPER_PASS
MYSQL_USER=$APP_USER
MYSQL_PASSWORD=$APP_PASS
MYSQL_DATABASE=$DB_NAME
RDS_INSTANCE_ID=$DB_INSTANCE_ID
ALIBABA_REGION=$REGION
EOF
  chmod 600 "$SECRETS_FILE"
  echo "bootstrap-rds: wrote new secrets to $SECRETS_FILE"
else
  # shellcheck disable=SC1090
  source "$SECRETS_FILE"
  echo "bootstrap-rds: reusing secrets from $SECRETS_FILE"
fi

# shellcheck disable=SC1090
source "$SECRETS_FILE"

aliyun_rds() {
  node "$ROOT/deploy/aliyun-rds-api.mjs" "$@"
}

wait_for_account() {
  local name="$1"
  local tries=30
  while (( tries > 0 )); do
    if aliyun_rds describe-accounts | grep -q "\"AccountName\":\"$name\""; then
      return 0
    fi
    sleep 5
    tries=$((tries - 1))
  done
  return 1
}

echo "bootstrap-rds: checking accounts on $DB_INSTANCE_ID ..."
ACCOUNTS_JSON="$(aliyun_rds describe-accounts)"

if ! echo "$ACCOUNTS_JSON" | grep -q "\"AccountName\":\"$SUPER_USER\""; then
  echo "bootstrap-rds: creating super account $SUPER_USER ..."
  aliyun_rds create-account --name "$SUPER_USER" --password "$RDS_SUPER_PASSWORD" --type Super
  wait_for_account "$SUPER_USER"
fi

if ! echo "$ACCOUNTS_JSON" | grep -q "\"AccountName\":\"$APP_USER\""; then
  echo "bootstrap-rds: creating app account $APP_USER ..."
  aliyun_rds create-account --name "$APP_USER" --password "$MYSQL_PASSWORD" --type Normal
  wait_for_account "$APP_USER"
fi

if ! aliyun_rds describe-databases | grep -q "\"DBName\":\"$DB_NAME\""; then
  echo "bootstrap-rds: creating database $DB_NAME ..."
  aliyun_rds create-database --name "$DB_NAME"
  sleep 3
fi

if ! aliyun_rds describe-accounts | grep -q "\"DBName\":\"$DB_NAME\""; then
  echo "bootstrap-rds: granting ReadWrite on $DB_NAME to $APP_USER ..."
  aliyun_rds grant-privilege --account "$APP_USER" --database "$DB_NAME" --privilege ReadWrite
fi

echo "bootstrap-rds: ensuring public connection ..."
if ! aliyun_rds describe-net-info | grep -q '"IPType":"Public"'; then
  aliyun_rds allocate-public-connection --prefix "$PUBLIC_PREFIX"
  sleep 10
fi

DEV_IP="$(curl -sf --max-time 10 https://ifconfig.me/ip || curl -sf --max-time 10 https://api.ipify.org || true)"
if [[ -z "$DEV_IP" ]]; then
  echo "bootstrap-rds: warning: could not detect public IP; whitelist only vSwitch CIDR" >&2
  WHITELIST="127.0.0.1,${VSWITCH_CIDR}"
else
  echo "bootstrap-rds: whitelisting dev IP $DEV_IP and vSwitch $VSWITCH_CIDR"
  WHITELIST="127.0.0.1,${DEV_IP},${VSWITCH_CIDR}"
fi

aliyun_rds modify-security-ips --whitelist "$WHITELIST"

NET_JSON="$(aliyun_rds describe-net-info)"
PUBLIC_HOST="$(node -e "
const j=JSON.parse(process.argv[1]);
const nets=j.Items?.DBInstanceNetInfo||[];
const pub=nets.find(n=>n.IPType==='Public');
const priv=nets.find(n=>n.IPType==='Private');
console.log(JSON.stringify({publicHost:pub?.ConnectionString||'',privateHost:priv?.ConnectionString||''}));
" "$NET_JSON")"

PUBLIC_HOST_VAL="$(echo "$PUBLIC_HOST" | node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(j.publicHost||'');")"
PRIVATE_HOST_VAL="$(echo "$PUBLIC_HOST" | node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(j.privateHost||'');")"

{
  echo "MYSQL_HOST_PUBLIC=$PUBLIC_HOST_VAL"
  echo "MYSQL_HOST_PRIVATE=$PRIVATE_HOST_VAL"
} >> "$SECRETS_FILE"

echo "bootstrap-rds: done."
echo "  Public host:  $PUBLIC_HOST_VAL"
echo "  Private host: $PRIVATE_HOST_VAL"
echo "  App user:     $APP_USER / db $DB_NAME"
echo "  Secrets:      $SECRETS_FILE"
